spring:
  datasource:
    url: jdbc:mysql://localhost:3306/journal?useSSL=false&useUnicode=true&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
    username: springboot
    password: springboot
    driver-class-name: com.mysql.jdbc.Driver
    initialization-mode: always
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
      #naming:
      #  implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
      use-new-id-generator-mappings: false

  data:
    rest:
      base-path: /api

  security:

    user:
      name: springboot
      password: isawesome